export const LEAGUES = {
  PL: {
    id: "PL",
    name: "Premier League",
    emblem: "https://crests.football-data.org/PL.png",
    apiFootballLeagueId: 39,
    transfermarktCompetitionId: "GB1",
    espnLeagueCode: "eng.1",
  },
  ELC: {
    id: "ELC",
    name: "Championship",
    emblem: "https://crests.football-data.org/ELC.png",
    apiFootballLeagueId: 40,
    transfermarktCompetitionId: "GB2",
    espnLeagueCode: "eng.2",
  },
  SA: {
    id: "SA",
    name: "Serie A",
    emblem: "https://crests.football-data.org/SA.png",
    apiFootballLeagueId: 135,
    transfermarktCompetitionId: "IT1",
    espnLeagueCode: "ita.1",
  },
  PD: {
    id: "PD",
    name: "La Liga",
    emblem: "https://crests.football-data.org/PD.png",
    apiFootballLeagueId: 140,
    transfermarktCompetitionId: "ES1",
    espnLeagueCode: "esp.1",
  },
  BL1: {
    id: "BL1",
    name: "Bundesliga",
    emblem: "https://crests.football-data.org/BL1.png",
    apiFootballLeagueId: 78,
    transfermarktCompetitionId: "L1",
    espnLeagueCode: "ger.1",
  },
  FL1: {
    id: "FL1",
    name: "Ligue 1",
    emblem: "https://crests.football-data.org/FL1.png",
    apiFootballLeagueId: 61,
    transfermarktCompetitionId: "FR1",
    espnLeagueCode: "fra.1",
  },
  CL: {
    id: "CL",
    name: "Champions League",
    emblem: "https://crests.football-data.org/CL.png",
    apiFootballLeagueId: 2,
    transfermarktCompetitionId: "CL",
    espnLeagueCode: "uefa.champions",
  },
} as const;

export type LeagueId = keyof typeof LEAGUES;
